### PR TITLE
Started initial implementation of test case 001

### PR DESCRIPTION
**Pull request by ayhanhulagu**
will add more commits after, lets merge it

### CODE REVIEW

**Comment by ayhanhulagu** [comment]
Which part do you want to improve?

**Comment by Mrtdu25** [comment]
To be or not to be what is the question

**Comment by ayhanhulagu** [comment]
Hello guys

**Comment by Gulira91** [comment]
Great job !

**Comment by ayhanhulagu** [comment]
It works

**Comment by ayhanhulagu** [comment]
Selam kizlar!

**Pull request merged**
